// Exercice 2: GÃ©rer les erreurs avec try...catch
try {
       let resultat = 10 / 2;  
    console.log(resultat); 
} catch (erreur) {
     console.error("Une erreur s\'est produite : ", erreur);
}
